[package]
name = "trusty_core"
edition.workspace = true
rust-version.workspace = true
version.workspace = true
build = "build.rs"

[dependencies]
embedded-graphics.workspace = true
log.workspace = true
embedded-io = "0.6.1"

[build-dependencies]
resvg = "0.41"
usvg = "0.41"
tiny-skia = "0.11"
